blank_issues_enabled: false
contact_links:
  - name: Contact Developer
    url: https://t.me/AraafRoyall
    about: Directly Contact Developer on Telegram for Any Help
  - name: Cleaner Royall Bot
    url: https://t.me/CleanerRoyallbot
    about: Get help or Submit any Report and Assisted through Cleaner Royall Telegram Bot 
